config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :users
  get 'homes/activity'
  root 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :title, :short_description, :language, :price, :level, presence: true
validates :description, presence: true, length: { :minimum => 5 }

has_rich_text :description
belongs_to :user

extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]


  LANGUAGES = [:"English", :"Russian", :"Polish", :"Spanish"]
  def self.languages
    LANGUAGES.map { |language| [language, language] }
  end

  LEVELS = [:"Beginner", :"Intermediate", :"Advanced"]
  def self.levels
    LEVELS.map { |level| [level, level] }
  end

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable

         def to_s
          email
         end

         def username
          self.email.split(/@/).first
        end

         has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    include PublicActivity::StoreController #save current_user using gem public_activity

    before_action :set_global_variables, if: :user_signed_in?
    
    def set_global_variables
      @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search) #navbar search
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    if params[:title]
      @courses = Course.where('title ILIKE ?', "%#{params[:title]}%") #case-insensitive
    else
      @courses = Course.all

      @q = Course.ransack(params[:q])
      @courses = @q.result.includes(:user)
    end

    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    @courses = @ransack_courses.result.includes(:user)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :price, :language, :level)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 skip_before_action :authenticate_user!, :only => [:index]
  
 def index
    @courses = Course.all.limit(5)
    @latest_couses = Course.all.limit(3).order(created_at: :desc)
  end

  def activity
  @activities = PublicActivity::Activity.all
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
       #@users = User.all.order(created_at: :desc)
       #@users = User.all.limit(1)

       @q = User.ransack(params[:q])
       @users = @q.result(distinct: true)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for(flash_type)
        case flash_type
          when "success"
            "alert-success"
          when "error"
            "alert-danger"
          when "alert"
            "alert-warning"
          when "notice"
            "alert-info"
          else
            flash_type.to_s
          end
      end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.erb
<div class="card">
  <div class="card-header">
    <div class="fa fa-book"></div>
    <%= link_to course.title, course_path(course) %>
  </div>
  <div class="card-body">
    <%= course.description %>
  </div>
  <div class="card-footer">
  <div class="fa fa-globe-africa"></div>
  <%= course.language %>

  <div class="fa fa-signal"></div>
  <%= course.level %>
  <%= number_to_currency(course.price) %>
  </div>
  <div class="card-footer">
    <div class="far fa-clock"></div>
    <%= course.created_at.strftime('%d-%b-%Y') %>
    <div class="row"></div>
    <div class="fa fa-chalkboard-teacher"></div>
    <%= course.user.username %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', course, class: 'btn btn-sm btn-primary' %>
    <%= link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
  </div>
</div>

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.label :description %>
    <%= f.rich_text_area :description %>
    <small>
    <%= f.error :description, class: 'text-danger' %>
    </small>
    <%= f.input :short_description %>
    <%= f.input :language, collection: [ "English", "Polish", "Russian"] %>
    <%= f.input :level, collection: [ "Beginner", "Intermediate", "Advanced"] %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>UserID</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td><%= course.user %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="card-columns">
  <% @courses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<br/>


<%= link_to 'New Course', new_course_path %>




<h1></h1>
Courses:
<div class="card-columns">
  <% @courses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<div class="row">
  <div class="col-md-2">
    <!--
    <%= # search_form_for @q do |f| 
    %>
      <%= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f| %>
      <%= f.label :title %>
      <%= f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm' %>
      <%= f.label :description %>
      <%= f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm' %>
      <!--= f.search_field :language_cont, placeholder: 'Language', class: 'form-control form-control-sm'
      -->
      <!--= f.select :language_cont, ['English', 'Polish', 'Russian'], include_blank: true, class: 'form-control form-control-sm'
      -->
      <%= f.label :language %>
      <%= f.select :language_cont, Course.languages, include_blank: true %>
      <!--= f.search_field :level_cont, placeholder: 'Level', class: 'form-control form-control-sm'
      -->
      <%= f.label :level %>
      <%= f.select :level_cont, Course.levels, include_blank: true %>
      <%= f.label :price %>
      <%= f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm' %>
      <%= f.label :teacher %>
      <%= f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm' %>
      <%= f.submit %>
    <% end %>
    <%= link_to 'refresh', courses_path %>
  </div>
  <div class="col-md-10">
    <div class="card-columns">
      <% @courses.each do |course| %>
        <%= render 'courses/course', course: course %>
      <% end %>
    </div>
  </div>
</div>
<br/>

app/views/courses/new.html.erb
<div class="card">
    <div class="card-header">
        <h1>New Course</h1>
    </div>
    <div class="card-body">
        <%= render 'form', course: @course %>
    </div>
    <div class="card-footer">
        <%= link_to 'Back', courses_path, class: 'btn btn-info' %>
    </div>
</div>

app/views/courses/show.html.erb
<div class="card-columns">
  <%= render 'courses/course', course: @course %>
  
</div>

app/views/homes/activity.html.erb
<h3>
  <div class="text-center">
    Activity
    <div class="badge badge-info">
      <%= @activities.count %>
    </div>
  </div>
</h3>
<p></p>
<ul class="list-group">
  <% @activities.each do |activity| %>
    <li class="list-group-item">
      <%= activity.id %>
      <%= activity.trackable_type %>
      <%= activity.trackable_id %>
      <%= link_to activity.trackable, activity.trackable %>
      <%= activity.key %>
      <%= activity.parameters %>
      <%= activity.owner %>
    </li>
  <% end %>
</ul>

app/views/homes/index.html.erb
<div class="jumbotron">
    <div class="display-4">
        What do you want to learn today?
    </div>
    <div class="p-4"></div>

    <%= link_to root_path do %>
    <div class="fa fa-home"></div>
    <div class="form-inline my-2 my-lg-0">
        <%= form_tag(courses_path, method: :get) do %>
        <div class="input-group">
            <%= text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm' %>
            <span class="input-group-append">
                <button class="btn btn-primary btn-sm" type="submit">
                    <span aria-hidden="true" class="fa fa-search"></span>
                </button>
            </span>
        </div>
        <% end %>
    </div>
    <% end %>
</div>
<div class="card-group">
    <div class="card card-body">
        <h1>
            <div class="fa fa-graduation-cap"></div>
        </h1>
        <%= Course.count %>
        online courses
        <div class="row"></div>
        Explore a variety of fresh topics
    </div>
    <div class="card card-body">
        <h1>
            <div class="fa fa-chalkboard-teacher"></div>
            <!--.fa.fa-brain
      -->
        </h1>
        <%= Course.distinct.count(:user_id) %>
        expert instructors
        <div class="row"></div>
        Find the right instructor for you
    </div>
    <div class="card card-body">
        <h1>
            <div class="fa fa-user-graduate"></div>
        </h1>
        <%= User.count %>
        active learners
        <div class="row"></div>
        Join the knowledge sharing community
    </div>
    <div class="card card-body">
        <h1>
            <div class="fa fa-infinity"></div>
        </h1>
        Lifetime access
        <div class="row"></div>
        Learn on your schedule
    </div>
</div>
<hr />
<h2>
    Popular courses
</h2>
<div class="card-columns">
    <% @courses.each do |course| %>
    <%= render 'courses/course', course: course %>
    <% end %>
</div>
<hr />
<h2>
    Top rated courses
</h2>
<div class="card-columns">
    <% @courses.each do |course| %>
    <%= render 'courses/course', course: course %>
    <% end %>
</div>
<hr />
<h2>
    Latest courses
</h2>
<div class="card-columns">
    <% @latest_couses.each do |course| %>
    <%= render 'courses/course', course: course %>
    <% end %>
</div>
<hr />

app/views/layouts/_footer.html.erb
<hr>
<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-md-4'>
        Copyright
        ©
        Masitbd.com.
        <div class='row'></div>
        <div class='fa fa-envelope'></div>
        <div class='row'></div>
      </div>
      <div class='col-md-4'>
        Privacy policy
        <div class='row'></div>
        Terms and conditions
      </div>
      <div class='col-md-4'>
        About us
        <div class='row'></div>
      </div>
    </div>
  </div>
</footer>
<br>

app/views/layouts/_header.erb
<% if current_user %>
  <%= current_user.email %>
  <%= link_to 'Account settings', edit_user_registration_path %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign Up', new_user_registration_path %>
  <%= link_to 'Log In', new_user_session_path %>
<% end %>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Resturent Management Systems", root_path, class: "navbar-brand" %>
  <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if current_user %>
      <ul class="navbar-nav mr-auto">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Home
          <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(courses_path) %> nav-item">
          <%= link_to courses_path, class: 'nav-link' do %>
            <div class="fa fa-book"></div>
            Courses
          <% end %>
        </li>
      </ul>
      <div class="form-inline my-2 my-lg-0">
        <%= form_tag(root_path, method: :get) do %>
          <div class="input-group">
            <%= text_field_tag :name, params[:name], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm' %>
            <span class="input-group-append">
              <button class="btn btn-primary btn-sm" type="submit">
                <span aria-hidden="true" class="fa fa-search"></span>
              </button>
            </span>
          </div>
        <% end %>
      </div>
      <ul class="navbar-nav mr-right">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Another link
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
            <b>
              <%= current_user.email %>
            </b>
          </a>
          <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <div class="fa fa-cog"></div>
              <b>Account settings</b>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <div class="fa fa-sign-out-alt"></div>
              <b>Sign out</b>
            <% end %>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= message %>
    </div>
  <% end %>

app/views/layouts/_navbar.erb
<% if current_user %>
  <%= current_user.email %>
  <%= link_to 'Account settings', edit_user_registration_path %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign Up', new_user_registration_path %>
  <%= link_to 'Log In', new_user_session_path %>
<% end %>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Resturent Management Systems", root_path, class: "navbar-brand" %>
  <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if current_user %>
      <ul class="navbar-nav mr-auto">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Home
          <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(courses_path) %> nav-item">
          <%= link_to courses_path, class: 'nav-link' do %>
            <div class="fa fa-book"></div>
            Courses
          <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(new_course_path) %> nav-item">
  <%= link_to new_course_path, class: 'nav-link' do %>
    <div class="fa fa-plus"></div>
    New Course
  <% end %>
</li>

<li class="<%= 'active font-weight-bold' if current_page?(users_path) %> nav-item">
  <%= link_to users_path, class: 'nav-link' do %>
    <div class="fa fa-users"></div>
    Users
  <% end %>
</li>
<li class="<%= 'active font-weight-bold' if current_page?(homes_activity_path) %> nav-item">
  <%= link_to homes_activity_path, class: 'nav-link' do %>
    <div class="fa fa-bell"></div>
    Activity
  <% end %>
</li>


      </ul>
      
      <%= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f| %>
        <div class="input-group">
          <%= f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off %>
          <span class="input-group-append">
            <button class="btn btn-primary btn-sm" type="submit">
              <span aria-hidden="true" class="fa fa-search"></span>
            </button>
          </span>
        </div>
      <% end %>
</div>
<!--
      <div class="form-inline my-2 my-lg-0">
        <%= form_tag(courses_path, method: :get) do %>
          <div class="input-group">
            <%= text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm' %>
            <span class="input-group-append">
              <button class="btn btn-primary btn-sm" type="submit">
                <span aria-hidden="true" class="fa fa-search"></span>
              </button>
            </span>
          </div>
        <% end %>
      </div>

      -->
      <ul class="navbar-nav mr-right">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Another link
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
            <b>
              <%= current_user.email %>
            </b>
          </a>
          <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <div class="fa fa-cog"></div>
              <b>Account settings</b>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <div class="fa fa-sign-out-alt"></div>
              <b>Sign out</b>
            <% end %>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>Rms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/messages' %>
  <div class="container">
     <%= yield %>
   </div>
  </body>
</html>
<%= render 'layouts/footer' %>

app/views/users/_user.html.erb
<div class="card">
    <div class="card-header">
        <div class="fa fa-user"></div>
        <%= user.email %>
    </div>
    <div class="card-footer">
        Signed up
        <%= time_ago_in_words(user.created_at) %>
        ago
    </div>
    <div class="card-footer">
  Confirmed email?
  <% if user.confirmed_at.present? %>
    <div class="badge badge-success">Yes</div>
  <% else %>
    <div class="badge badge-danger">No</div>
  <% end %>
</div>
'
    
</div>

app/views/users/index.html.erb
<!-- 
<div class="card-columns">
  <% @users.each do |user| %>
    <%= render 'users/user', user: user  %>
  <% end %>
</div>
-->

<div class="card-columns">
  <% @users.each do |user| %>
    <%= render 'users/user', user: user  %>
   
  <% end %>
</div>
<div class="form-inline">
  <%= search_form_for @q do |f| %>
    <%= f.search_field :email_cont, placeholder: 'email' %>
    <%= f.search_field :sign_in_count_eq, placeholder: 'sign in count' %>
    <%= f.search_field :email_or_sign_in_count_eq, placeholder: 'email or sign in count' %>
    <%= f.submit %>
  <% end %>
  <div class="ml-2"></div>
  <%= link_to 'refresh', users_path %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>
        <%= sort_link(@q, :email) %>
      </th>
      <th>created_at</th>
      <th>
        <%= 'sign_in_count'.humanize %>
      </th>
      <th>
        <%= 'current_sign_in_at'.humanize %>
      </th>
      <th>
        <%= 'last_sign_in_at'.humanize %>
      </th>
      <th>
        <%= 'current_sign_in_ip'.humanize %>
      </th>
      <th>
        <%= 'last_sign_in_ip'.humanize %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.id %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user.created_at %>
        </td>
        <td>
          <%= user.sign_in_count %>
        </td>
        <td>
          <%= user.current_sign_in_at %>
        </td>
        <td>
          <%= user.last_sign_in_at %>
        </td>
        <td>
          <%= user.current_sign_in_ip %>
        </td>
        <td>
          <%= user.last_sign_in_ip %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>